import { drizzle } from 'drizzle-orm/postgres-js';
import { sql } from 'drizzle-orm';
import { jsonSafe } from './json';
import postgres from 'postgres';
import * as baseSchema from './schema';
import * as inventorySchema from './schema/inventory';
import * as outboxSchema from './schema/outbox';
import * as orgSettingsSchema from './schema/orgSettings';
import * as etaInvoicesSchema from './schema/etaInvoices';
import * as couriersSchema from './schema/couriers';
import * as returnsSchema from './schema/returns';
import * as purchasingSchema from './schema/purchasing';
import * as customersSchema from './schema/customers';
import * as couponsSchema from './schema/coupons';
import * as stocktakingSchema from './schema/stocktaking';
import * as pricelistsSchema from './schema/pricelists';
import * as shippingZonesSchema from './schema/shippingZones';
import * as campaignsSchema from './schema/campaigns';
import * as giftCardsSchema from './schema/giftCards';
import * as customerSegmentsSchema from './schema/customerSegments';
import * as orgFeatureFlagsSchema from './schema/orgFeatureFlags';
import * as documentCountersSchema from './schema/documentCounters';
import * as idempotencySchema from './schema/idempotency';
import * as ledgerSchema from './schema/ledger';
// Better Auth's own tables. Generated by @better-auth/cli, not hand-written —
// the adapter matches on exact table and column names, so guessing them is how
// auth silently half-works.
import * as authSchema from './schema/auth';

const schema = { ...baseSchema, ...inventorySchema, ...outboxSchema, ...orgSettingsSchema, ...etaInvoicesSchema, ...couriersSchema, ...returnsSchema, ...purchasingSchema, ...customersSchema, ...couponsSchema, ...stocktakingSchema, ...pricelistsSchema, ...shippingZonesSchema, ...campaignsSchema, ...giftCardsSchema, ...customerSegmentsSchema, ...orgFeatureFlagsSchema, ...documentCountersSchema, ...idempotencySchema, ...ledgerSchema, ...authSchema };
import { auditLog } from './schema';

export * from './json';
export * from './permissions';
export * from './schema';
// Better Auth's tables. Exported here so consumers join against them by name
// rather than reaching through '@irth/db/src/schema/auth' — no name collides
// with the other schema modules.
export * from './schema/auth';
export * from './schema/inventory';
export * from './schema/outbox';
export * from './schema/orgSettings';
export * from './schema/etaInvoices';
export * from './schema/inventoryDiscrepancies';
export * from './schema/couriers';
export * from './schema/returns';
export * from './schema/purchasing';
export * from './schema/customers';
export * from './schema/coupons';
export * from './schema/stocktaking';
export * from './schema/pricelists';
export * from './schema/shippingZones';
export * from './schema/campaigns';
export * from './schema/giftCards';
export * from './schema/customerSegments';
export * from './schema/orgFeatureFlags';
export * from './schema/documentCounters';
export * from './schema/idempotency';
export * from './schema/ledger';
export * from './ledger';
export * from './orderLedger';
export * from './costing';
export * from './idempotency';
export * from './orgContext';
export * from './etaOrderInput';
// The outbox WRITER, beside './schema/outbox' which is the table. Same split as
// idempotency.ts / schema/idempotency.ts: producers import emitOutboxEvent, the
// worker imports outboxEvents, and neither has to know where the other lives.
export * from './outbox';

export const createDb = (url: string) => {
  const client = postgres(url, { prepare: false });
  return drizzle(client, { schema });
};

export type DbInstance = ReturnType<typeof createDb>;

let _dbInstance: DbInstance | null = null;
function realDb(): DbInstance {
  if (!_dbInstance) {
    _dbInstance = createDb(process.env.DATABASE_URL!);
  }
  return _dbInstance;
}

/**
 * Lazy so a bare `import { db } from '@irth/db'` does NOT open a Postgres
 * connection (or parse DATABASE_URL) at module-load time.
 *
 * Next.js's build step ("Collecting page data") imports every route module
 * to statically analyze it, and Vercel does not expose "Sensitive"
 * environment variables during build — only at runtime, inside an actual
 * request (confirmed by testing: `pnpm run build` failed with
 * `TypeError: Invalid URL` on `undefined` at every route importing `db`,
 * the first time DATABASE_URL was added to Vercel as a Sensitive var,
 * because the eager `createDb(process.env.DATABASE_URL!)` this replaced ran
 * during that build-time import with an empty process.env).
 *
 * A Proxy defers both the env read and the real connection until the first
 * property access, which for every caller in this codebase only ever
 * happens inside a request handler — never at import time. `get` binds
 * function properties to the real instance so `db.select()` etc. do not see
 * the Proxy as `this`; non-function properties (`db.query`, already a
 * fully-formed object with its own correctly-bound methods) pass through
 * unchanged.
 */
export const db: DbInstance = new Proxy({} as DbInstance, {
  get(_target, prop, _receiver) {
    const instance = realDb();
    const value = Reflect.get(instance as object, prop, instance);
    return typeof value === 'function' ? value.bind(instance) : value;
  },
});

/**
 * Runs `fn` in a transaction that the database will only let touch one tenant's
 * rows (CLAUDE.md rule 3).
 *
 * Two statements do the work, and both are transaction-local for the same
 * reason: `db` above is a module-level singleton over a shared pool, so
 * anything set at connection level outlives the request and leaks into whoever
 * gets that connection next.
 *
 *   SET LOCAL ROLE irth_app
 *     The connecting role (`neondb_owner`) owns every table AND has
 *     rolbypassrls, so policies do not apply to it — measured, not assumed:
 *     with a policy in place and the context scoped to one of two orgs, the
 *     owner still saw both rows, and FORCE ROW LEVEL SECURITY did not change
 *     that. BYPASSRLS wins over FORCE. Dropping to `irth_app`, which owns
 *     nothing and has no bypass, made the same query return one row.
 *
 *   set_config('app.org_id', $1, true)
 *     The value every policy compares against. The third argument is what makes
 *     it local to the transaction.
 *
 * Both revert on COMMIT and on ROLLBACK, so a failed request cannot leave a
 * connection elevated or scoped to a stale tenant.
 *
 * This is defence in depth, not a replacement for `eq(table.orgId, ctx.orgId)`.
 * Queries should still be scoped explicitly; RLS is what catches the one that
 * is not.
 */
export async function withOrgContext<T>(
  dbInstance: DbInstance,
  orgId: string,
  fn: (tx: Parameters<Parameters<DbInstance['transaction']>[0]>[0]) => Promise<T>,
): Promise<T> {
  // Fail before opening a transaction rather than handing a malformed value to
  // a policy comparison, where it would surface as a confusing cast error.
  if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(orgId)) {
    throw new TypeError(`withOrgContext requires a uuid orgId, got ${JSON.stringify(orgId)}`);
  }

  return dbInstance.transaction(async (tx) => {
    // One statement, not two. `SET LOCAL ROLE x` is just `SET LOCAL role = x`,
    // and set_config(name, value, is_local=true) is the function form of SET
    // LOCAL — so both GUCs can be set in a single round trip. Every wrapped
    // procedure pays this cost, so halving it is worth the indirection.
    //
    // Setting the role through set_config also keeps the org id a bound
    // parameter: `SET LOCAL ROLE` takes an identifier, which cannot be
    // parameterised, so a two-statement version invites string interpolation
    // the day someone makes the role dynamic.
    //
    // Both are transaction-local, so nothing leaks to the next request sharing
    // this pooled connection — asserted in integration/tenantIsolation.test.ts.
    await tx.execute(
      sql`SELECT set_config('role', 'irth_app', true), set_config('app.org_id', ${orgId}, true)`,
    );
    return fn(tx);
  });
}

/** The handle drizzle hands a `db.transaction()` callback. */
export type DbTx = Parameters<Parameters<DbInstance['transaction']>[0]>[0];

/**
 * A transaction handle — NOT the plain db.
 *
 * `rollback` is what makes this refuse a non-transaction: PgTransaction has it,
 * PostgresJsDatabase does not, so `withAudit(db, …)` and `withAudit(ctx.db, …)`
 * stop compiling. It is never called here; it is in the type purely so the
 * compiler can tell the two apart.
 *
 * Previously this was `Pick<DbInstance, 'insert'>`, which both satisfy. That
 * let a business write and its audit row commit as two separate autocommits:
 * a failure between them left a change with no record that it happened, and no
 * report anywhere would show the gap. Making it a compile error is the only
 * version of this rule that holds — a convention did not.
 */
type AuditWriter = Pick<DbTx, 'insert' | 'rollback'>;

export async function withAudit<T extends { id?: string }>(
    dbInstance: AuditWriter,
    operation: () => Promise<T>,
    auditData: { orgId: string, userId: string | null, action: string, tableName: string, changes: Record<string, unknown> }
) {
    const result = await operation();
    // `?? null`, not `|| 'unknown_id'`. record_id is uuid, so the old string
    // fallback raised Postgres 22P02 and threw instead of writing an audit row
    // (see migration 0033). NULL says "this action had no single subject row" —
    // true for bulk updates — and `changes` carries the detail either way.
    //
    // `??` not `||` on purpose: an empty-string id is a bug worth surfacing as
    // a constraint violation, not silently converting to NULL.
    const recordId = result?.id ?? null;
    // `changes` lands in a jsonb column, and the postgres driver serializes
    // jsonb parameters with JSON.stringify — which THROWS on bigint. Since
    // money became bigint minor units (0028), a changeset mentioning any amount
    // took down the write it was supposed to record. jsonSafe renders bigint as
    // a decimal string; applied here, at the boundary, so no call site has to
    // remember.
    await dbInstance.insert(auditLog).values({
        ...auditData,
        changes: jsonSafe(auditData.changes),
        recordId,
    });
    return result;
}

/** Document kinds with their own per-tenant number series. */
export type DocumentKind = 'order' | 'return' | 'purchase_order';

/**
 * Claims the next document number for a tenant, atomically.
 *
 * MUST be called inside a transaction — pass the `tx` from `withOrgContext`.
 * The number is claimed by the same transaction that writes the document, so a
 * rollback releases it and the series stays gapless. Calling this outside a
 * transaction would autocommit the increment and burn the number on any later
 * failure, which is the behaviour a Postgres SEQUENCE has and the reason this
 * is not one.
 *
 * Concurrency: the ON CONFLICT DO UPDATE takes a row lock on (org_id, kind), so
 * two concurrent callers for the same tenant and kind serialise here rather
 * than both reading the same value. That is the whole point — it replaces
 *
 *     SELECT count(*) FROM orders WHERE org_id = $1   -- N
 *     ...insert with N + 1
 *
 * which at READ COMMITTED let both callers see N and both build N+1.
 *
 * The lock is per (tenant, kind), so tenants never block each other and an
 * order never blocks a purchase order.
 *
 * Single statement, so there is no window between reading and writing for
 * anything to interleave. Do not "optimise" this into a SELECT followed by an
 * UPDATE.
 */
export async function nextDocumentNumber(
    tx: Pick<DbTx, 'execute' | 'rollback'>,
    orgId: string,
    kind: DocumentKind,
): Promise<number> {
    const rows = await tx.execute<{ last_value: string | number | bigint }>(sql`
        INSERT INTO org_document_counters (org_id, kind, last_value, updated_at)
        VALUES (${orgId}, ${kind}, 1, now())
        ON CONFLICT (org_id, kind) DO UPDATE
            SET last_value = org_document_counters.last_value + 1,
                updated_at = now()
        RETURNING last_value
    `);

    const [row] = [...rows];
    if (!row) {
        // Unreachable via the statement above, which always returns a row —
        // unless RLS filtered it out, which means the caller did not go through
        // withOrgContext and app.org_id is unset. Fail loudly rather than
        // returning NaN and writing a document numbered "undefined".
        throw new Error(
            `nextDocumentNumber(${kind}) returned no row for org ${orgId}. ` +
                'This usually means the call is not inside withOrgContext, so the ' +
                'RLS policy on org_document_counters matched nothing.',
        );
    }

    // postgres-js returns bigint columns as strings by default; Number is exact
    // for document numbers, which stay far below 2^53.
    return Number(row.last_value);
}

/**
 * Formats a claimed number the way each document kind is presented.
 *
 * Kept beside the allocator so the format and the series that feeds it cannot
 * drift apart — and so the seed logic in 0036, which reads the TRAILING digits
 * of these strings, has one place to check against.
 */
export function formatDocumentNumber(kind: DocumentKind, value: number, year?: number): string {
    const seq = String(value).padStart(4, '0');
    switch (kind) {
        // The year is part of the label, not part of the series: the counter is
        // not reset in January. Changing that means seeding a new counter row,
        // not changing this string.
        case 'order':
            return `IRT-${year ?? new Date().getFullYear()}-${seq}`;
        case 'return':
            return `RMA-${seq}`;
        // PO carries a year and orders do not — matching what each has already
        // issued. Dropping the year here would renumber every existing PO's
        // shape and break the 0036 seed's continuity with them.
        case 'purchase_order':
            return `PO-${year ?? new Date().getFullYear()}-${seq}`;
    }
}
