'use client';
import { formatMoney, fromMinor, toDecimalString } from '@irth/domain';
import { useState } from "react";
import { trpc } from "@/lib/trpc";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { PermissionGate } from "@/components/PermissionGate";
import { ConfirmDialog } from "@/components/ui/ConfirmDialog";
import { Pagination } from "@/components/ui/Pagination";
import { SkeletonRow } from "@/components/ui/skeleton";
import { toast } from "sonner";
import { EmptyState } from '@/components/ui/EmptyState';
import { Box, Search } from 'lucide-react';

export interface Product { id:string; name:string; sku:string; priceMinor:bigint; stock:number; status:string; category:string|null; brand:"irth"; }
export interface Category { id:string; name:string; slug:string; parentId:string|null; }

export function ProductsClient({ products: initialProducts, categories }: { products: Product[], categories: Category[] }) {
 const [searchQuery,setSearchQuery]=useState(""); const [statusFilter,setStatusFilter]=useState("all"); const [page,setPage]=useState(1); const [isModalOpen,setIsModalOpen]=useState(false);
 const [editingId,setEditingId]=useState<string|null>(null); const [formName,setFormName]=useState(""); const [formNameAr,setFormNameAr]=useState(""); const [formSku,setFormSku]=useState(""); const [formPrice,setFormPrice]=useState(""); const [formStatus,setFormStatus]=useState("active"); const [formCategoryId,setFormCategoryId]=useState("");
 const PAGE_SIZE=50; const utils=trpc.useUtils();
 const {data:productsData,isFetching}=trpc.products.list.useQuery({page,pageSize:PAGE_SIZE,q:searchQuery,status:statusFilter==='all'?undefined:statusFilter},{initialData:{data:initialProducts,meta:{total:initialProducts.length,page:1,pageSize:PAGE_SIZE},error:null}});
 const products=productsData?.data||initialProducts; const total=productsData?.meta?.total??products.length;
 const createMutation=trpc.products.create.useMutation({onSuccess:()=>{toast.success("تم إنشاء المنتج بنجاح");utils.products.list.invalidate();setIsModalOpen(false);resetForm();},onError:(e:unknown)=>toast.error(e instanceof Error?e.message:"حدث خطأ أثناء إنشاء المنتج")});
 const updateMutation=trpc.products.update.useMutation({onSuccess:()=>{toast.success("تم تحديث المنتج بنجاح");utils.products.list.invalidate();setIsModalOpen(false);resetForm();},onError:(e:unknown)=>toast.error(e instanceof Error?e.message:"حدث خطأ أثناء تحديث المنتج")});
 const deactivateMutation=trpc.products.deactivate.useMutation({onSuccess:()=>{toast.success("تم تعطيل المنتج");utils.products.list.invalidate();},onError:(e:unknown)=>toast.error(e instanceof Error?e.message:"حدث خطأ أثناء التعطيل")});
 function resetForm(){setEditingId(null);setFormName("");setFormNameAr("");setFormSku("");setFormPrice("");setFormStatus("active");setFormCategoryId("");}
 function handleOpenEdit(p:Product){setEditingId(p.id);setFormName(p.name);setFormNameAr("");setFormSku(p.sku);setFormPrice(toDecimalString(fromMinor(p.priceMinor)));setFormStatus(p.status);const cat=categories.find(c=>c.name===p.category);setFormCategoryId(cat?.id||"");setIsModalOpen(true);}
 function handleSave(){const payload={name:formName,nameAr:formNameAr||undefined,sku:formSku,price:parseFloat(formPrice)||0,status:formStatus,categoryId:formCategoryId||undefined}; editingId?updateMutation.mutate({id:editingId,...payload}):createMutation.mutate({...payload,stock:0});}
 const status=(s:string)=>s==='active'?<Badge style={{backgroundColor:'var(--emerald)'}}>نشط</Badge>:s==='draft'?<Badge style={{backgroundColor:'var(--gold)'}}>مسودة</Badge>:<Badge variant="outline">مؤرشف</Badge>;
 return <div className="space-y-5">
  <header className="flex flex-col gap-4 border-b border-[var(--rim1)] pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-1 text-[10px] font-semibold tracking-[0.18em] text-[var(--t2)]">CATALOG / PRODUCTS</p><h1 className="text-2xl font-semibold tracking-tight text-[var(--t1)]">إدارة المنتجات</h1><p className="mt-1 text-xs text-[var(--t2)]">كتالوج المنتجات والحالة والمخزون في مساحة تشغيل واحدة.</p></div><PermissionGate resource="products" action="write"><Dialog open={isModalOpen} onOpenChange={o=>{setIsModalOpen(o);if(!o)resetForm();}}><DialogTrigger asChild><Button className="bg-[var(--t1)] text-[var(--surface)] hover:opacity-90">منتج جديد</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>{editingId?'تعديل منتج':'منتج جديد'}</DialogTitle></DialogHeader><div className="space-y-4 py-4"><div className="space-y-2"><Label>الاسم</Label><Input value={formName} onChange={e=>setFormName(e.target.value)}/></div><div className="space-y-2"><Label>الاسم (بالعربية)</Label><Input value={formNameAr} onChange={e=>setFormNameAr(e.target.value)}/></div><div className="space-y-2"><Label>SKU</Label><Input value={formSku} onChange={e=>setFormSku(e.target.value)}/></div><div className="space-y-2"><Label>السعر</Label><Input type="number" step="0.01" value={formPrice} onChange={e=>setFormPrice(e.target.value)}/></div><div className="space-y-2"><Label>الحالة</Label><Select value={formStatus} onValueChange={setFormStatus}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="active">نشط</SelectItem><SelectItem value="draft">مسودة</SelectItem><SelectItem value="archived">مؤرشف</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>القسم</Label><Select value={formCategoryId} onValueChange={setFormCategoryId}><SelectTrigger><SelectValue placeholder="اختر القسم"/></SelectTrigger><SelectContent><SelectItem value="none">لا يوجد قسم</SelectItem>{categories.map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></div><Button onClick={handleSave} disabled={createMutation.isPending||updateMutation.isPending} className="w-full">{editingId?'حفظ التعديلات':'إنشاء المنتج'}</Button></div></DialogContent></Dialog></PermissionGate></header>
  <section className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="relative w-full sm:max-w-sm"><Search className="pointer-events-none absolute end-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[var(--t2)]"/><Input placeholder="بحث في المنتجات..." value={searchQuery} onChange={e=>{setSearchQuery(e.target.value);setPage(1)}} className="pe-9"/></div><div className="flex gap-1 overflow-x-auto border border-[var(--rim1)] bg-[var(--surface)] p-1">{[['all','الكل'],['active','نشط'],['draft','مسودة'],['archived','مؤرشف']].map(([v,l])=><Button key={v} variant={statusFilter===v?'default':'ghost'} size="sm" onClick={()=>{setStatusFilter(v);setPage(1)}}>{l}</Button>)}</div></section>
  <div className="overflow-hidden rounded-sm border border-[var(--rim1)] bg-[var(--surface)]"><div className="overflow-x-auto"><Table><TableHeader className="bg-[var(--raised)]"><TableRow><TableHead className="text-start">المنتج</TableHead><TableHead className="text-start">SKU</TableHead><TableHead className="text-start">السعر</TableHead><TableHead className="text-start">المخزون</TableHead><TableHead className="text-start">الحالة</TableHead><TableHead className="text-start">القسم</TableHead><TableHead className="text-end">الإجراء</TableHead></TableRow></TableHeader><TableBody>{isFetching&&products.length===0?<TableRow><TableCell colSpan={7}><div className="space-y-1"><SkeletonRow/><SkeletonRow/><SkeletonRow/><SkeletonRow/></div></TableCell></TableRow>:products.length===0?<TableRow><TableCell colSpan={7} className="p-0"><EmptyState icon={Box} title="لا توجد منتجات" hint="غيّر البحث أو أضف أول منتج."/></TableCell></TableRow>:products.map(p=><TableRow key={p.id} className="transition-colors hover:bg-[var(--raised)]/50"><TableCell className="font-medium text-[var(--t1)]">{p.name}</TableCell><TableCell className="font-mono text-xs text-[var(--t2)]" dir="ltr">{p.sku}</TableCell><TableCell className="tabular-nums text-[var(--t1)]" dir="ltr">{formatMoney(fromMinor(p.priceMinor))}</TableCell><TableCell className="tabular-nums text-[var(--t1)]">{p.stock}</TableCell><TableCell>{status(p.status)}</TableCell><TableCell className="text-[var(--t2)]">{p.category||'—'}</TableCell><TableCell><div className="flex justify-end gap-1"><PermissionGate resource="products" action="write"><Button variant="ghost" size="sm" onClick={()=>handleOpenEdit(p)}>تعديل</Button>{p.status==='active'&&<ConfirmDialog title="تعطيل المنتج" description={`سيتم تعطيل المنتج «${p.name}». لن يظهر للبيع بعد ذلك.`} confirmLabel="تعطيل" pending={deactivateMutation.isPending} onConfirm={()=>deactivateMutation.mutate({id:p.id})}><Button variant="ghost" size="sm" className="text-[var(--crimson)]">تعطيل</Button></ConfirmDialog>}</PermissionGate></div></TableCell></TableRow>)}</TableBody></Table></div></div>
  <Pagination page={page} pageSize={PAGE_SIZE} total={total} onPageChange={setPage}/>
 </div>;
}