-- Row-level security: tenant isolation enforced by the database.
--
-- WHY A SEPARATE ROLE IS NOT OPTIONAL
--
-- The application connects as `neondb_owner`, which owns every table AND has
-- rolbypassrls = true. Measured on a probe table holding one row for each of
-- two orgs, with app.org_id scoped to org A:
--
--     ENABLE ROW LEVEL SECURITY + policy   -> 2 rows visible   (should be 1)
--     + FORCE ROW LEVEL SECURITY           -> 2 rows visible   (still)
--
-- BYPASSRLS overrides FORCE. Policies written for that connection enforce
-- nothing while looking complete, which is worse than having none.
--
-- The fix is a restricted role the session drops into for the duration of a
-- transaction. Same probe, same policy:
--
--     as neondb_owner                      -> 2 rows
--     after SET LOCAL ROLE irth_app        -> 1 row            (correct)
--
-- `SET LOCAL ROLE` is transaction-scoped, so the role reverts on commit or
-- rollback and cannot leak to the next request sharing the pooled connection.
-- That is also why it beats rotating DATABASE_URL to the restricted role: no
-- new credential, nothing for an operator to get wrong, and the elevated role
-- remains available for migrations.
--
-- FORCE is still set on every table so that a future connection as an owner
-- without BYPASSRLS is also constrained.

-- The application role. NOLOGIN on purpose: nothing connects as it directly,
-- sessions reach it only through SET LOCAL ROLE.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'irth_app') THEN
    CREATE ROLE irth_app NOLOGIN;
  END IF;
END $$;--> statement-breakpoint

-- The connecting role must be a member of irth_app to SET ROLE to it.
DO $$
BEGIN
  EXECUTE format('GRANT irth_app TO %I', current_user);
END $$;--> statement-breakpoint

GRANT USAGE ON SCHEMA public TO irth_app;--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO irth_app;--> statement-breakpoint
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO irth_app;--> statement-breakpoint

-- Tables created after this migration inherit the same grants, so a new table
-- is not silently unreachable by the application.
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO irth_app;--> statement-breakpoint
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO irth_app;--> statement-breakpoint

-- Policies are generated by looping over the catalogue rather than written out
-- forty times: a hand-maintained list is one forgotten table away from a leak,
-- and the omission would be invisible.
--
-- `(select current_setting(...))` rather than a bare call: wrapping it makes
-- Postgres treat the value as an initPlan, evaluated once per query instead of
-- once per row.
DO $$
DECLARE
  t record;
BEGIN
  FOR t IN
    SELECT c.relname AS table_name
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relkind = 'r'
      AND EXISTS (
        SELECT 1 FROM information_schema.columns col
        WHERE col.table_schema = 'public'
          AND col.table_name = c.relname
          AND col.column_name = 'org_id'
      )
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t.table_name);
    EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', t.table_name);
    EXECUTE format('DROP POLICY IF EXISTS %I ON %I', t.table_name || '_tenant_isolation', t.table_name);
    -- USING gates reads and the pre-image of writes; WITH CHECK gates the
    -- post-image, so a row cannot be inserted or moved into another tenant.
    EXECUTE format(
      'CREATE POLICY %I ON %I USING (org_id = (SELECT current_setting(''app.org_id'', true))::uuid) WITH CHECK (org_id = (SELECT current_setting(''app.org_id'', true))::uuid)',
      t.table_name || '_tenant_isolation', t.table_name
    );
  END LOOP;
END $$;--> statement-breakpoint

-- `organizations` is the tenant root: it has no org_id, it IS the org.
ALTER TABLE "organizations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "organizations" FORCE ROW LEVEL SECURITY;--> statement-breakpoint
DROP POLICY IF EXISTS "organizations_tenant_isolation" ON "organizations";--> statement-breakpoint
CREATE POLICY "organizations_tenant_isolation" ON "organizations"
  USING (id = (SELECT current_setting('app.org_id', true))::uuid)
  WITH CHECK (id = (SELECT current_setting('app.org_id', true))::uuid);--> statement-breakpoint

-- Better Auth's tables (user, session, account, verification) are identity, not
-- tenant data, and are deliberately left without policies: a user must be
-- readable before we know which org they belong to. They are excluded by the
-- loop above because they have no org_id — this comment records that the
-- omission is a decision, not an oversight.
COMMENT ON TABLE "user" IS 'Better Auth identity. Intentionally not RLS-scoped: read before tenant is known.';
