name: (temp) List Vercel env
on: workflow_dispatch

jobs:
  list-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List env vars
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install --global vercel@latest
          vercel pull --yes --environment=production --token="$VERCEL_TOKEN"
          vercel env ls --token="$VERCEL_TOKEN"
          echo "---project.json---"
          cat .vercel/project.json
