name: (temp) Push DATABASE_URL to Vercel admin project
on: workflow_dispatch

jobs:
  push-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add DATABASE_URL to Vercel project
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npm install --global vercel@latest
          vercel pull --yes --environment=production --token="$VERCEL_TOKEN"
          echo "${{ secrets.DATABASE_URL }}" | vercel env add DATABASE_URL production --token="$VERCEL_TOKEN"
