name: (temp) Create R2 bucket
on: workflow_dispatch

jobs:
  create-bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Create irth-assets R2 bucket
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: npx wrangler@4 r2 bucket create irth-assets
