name: (temp) Push Vercel env var
on: workflow_dispatch

jobs:
  push-env:
    runs-on: ubuntu-latest
    steps:
      - name: Add BETTER_AUTH_SECRET to Vercel project
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npm install --global vercel@latest
          vercel pull --yes --environment=production --token="$VERCEL_TOKEN"
          echo "${{ secrets.BETTER_AUTH_SECRET_GEN }}" | vercel env add BETTER_AUTH_SECRET production --token="$VERCEL_TOKEN"
