name: Deploy All

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-all.yml'

jobs:
  deploy-api:
    uses: ./.github/workflows/deploy-api.yml
    secrets: inherit

  deploy-admin:
    needs: deploy-api
    uses: ./.github/workflows/deploy-admin.yml
    secrets: inherit
